export const API_ENDPOINTS = {
  LOGIN: '/login',
  REGISTER: '/register',
  LOGOUT: '/logout',
  FORGET_PASSWORD: '/forget-password',
  PRODUCT: '/web/patient/medicine-details/',
  BEST_SELLER_PRODUCTS: '/web/patient/medicine-homepage-products/',
  BANNER_API: '/web/patient/medicine-page-top-slider/',
  BEST_SELLER_GROCERY_PRODUCTS: '/web/patient/medicine-homepage-products/',
  CATEGORY_PRODUCTS: '/web/patient/category-products/',
  POPCORN_JERKY_PRODUCTS: '/products_popcorn_jerky.json',
  FRESH_VEGETABLES_PRODUCTS: '/products_fresh_vegetables.json',
  SEARCH: '/web/patient/search-medicines/',
  ORDERS: '/patient/medicine-orders/',
  ADDRESS: '/patient/address/',
  PROFILE: '/patient/profile/',
  CONTACTUS: '/website/contact-us/',
  DEPARTMENT: '/patient/department/',
  DOCTOR: '/patient/department/',
  CART: '/web/patient/medicine-cart-details/',
  PAYMENTINFO: '/patient/medicine-order-payment/',
  ORDERIMAGE: '/patient/medicine-orders/',
  SUBSCRIBE: '/website/subscriber/',
};
