export const API_ENDPOINTS = {
  LOGIN: '/patient/login/',
  REGISTER: '/patient/register/',
  LOGOUT: '/logout',
  FORGET_PASSWORD: '/forget-password',
  PRODUCT: '/web/patient/medicine-details/',
  HOME_PRODUCTS: '/web/patient/medicine-homepage-products/',
  BANNER_API: '/web/patient/medicine-page-top-slider/',
  BEST_SELLER_PRODUCTS: 'web/patient/best-selling-product/',
  CATEGORY_PRODUCTS: '/web/patient/category-products/',
  SEARCH: '/web/patient/search-medicines/',
  ORDERS: '/patient/medicine-orders/',
  ADDRESS: '/patient/address/',
  PROFILE: '/patient/profile/',
  CONTACTUS: '/website/contact-us/',
  DEPARTMENT: '/patient/department/',
  DOCTOR: '/patient/department/',
  CART: '/web/patient/medicine-cart-details/',
  PAYMENTINFO: '/patient/medicine-order-payment/',
  ORDERIMAGE: '/patient/medicine-orders/',
  SUBSCRIBE: '/website/subscriber/',
  CART_API: '/patient/cart/',
  CATEGORIES: 'patient/medicine-categories/',
};
